# Generated by Django 4.1.8 on 2023-04-10 19:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Home Address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
