# Generated by Django 4.1.8 on 2023-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0005_user_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.project"
            ),
        ),
    ]
