language: python
python:
  - "3.10"
services:
  - postgresql

addons:
  postgresql: "14"
  apt:
    packages:
      - postgresql-14-postgis-3
      - gdal-bin
      - libgdal-dev

env:
  global:
    - DJANGO_SETTINGS_MODULE=portfolio.config.settings.test
    - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - pip install -r requirements/local.txt

before_script:
  - psql -c 'create database portfolio;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - gdalinfo --version

script:
  - mypy portfolio
  - pytest
