language: python
python:
  - "3.10"
services:
  - postgresql
addons:
  postgresql: "14"
env:
  global:
    - DJANGO_SETTINGS_MODULE=portfolio.settings.test
    - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
install:
  - sudo apt-get update
  - sudo apt-get install -y binutils libproj-dev gdal-bin
  - pip install -r requirements/local.txt
before_script:
  - psql -c 'create database portfolio_test;' -U postgres
script:
  -
