# Generated by Django 4.1.8 on 2023-04-13 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLocation",
        ),
    ]
